name: flutter_env_creator
description: Automatically generates dart code from your yaml file.
version: 2.0.1
repository: https://github.com/alex-80/flutter_env_creator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  path: ^1.8.0
  belatuk_merge_map: ^5.0.0
  mustache_template: ^2.0.0
  source_gen: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
