name: flutter_env_creator
description: Automatically generates dart code from your yaml file.
version: 2.0.0
repository: https://github.com/alex-80/flutter_env_creator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  path: ^1.8.0
  merge_map: ^1.0.2
  mustache: ^1.1.1
  source_gen: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
